apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git-lab.meioambiente.mg.gov.br/semad/argocd.git
    path: argocd
    targetRevision: HEAD
    helm:
      valuesFiles: []
    # directory:
    #   recurse: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  # sourceRef:
  #   secretRef:
  #     name: gitlab-creds  # Nome do Secret contendo suas credenciais
  #     namespace: argocd
  #     usernameKey: username
  #     passwordKey: password
  



