apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: conversao
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/josefmarques/web-color-deploy.git
    targetRevision: HEAD
    path: kustomize
  destination:
    namespace: kubernetes
    server: https://kubernetes.default.svc












