

apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server-nodeport
    app.kubernetes.io/part-of: argocd
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: 30080
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
      nodePort: 30443
  selector:
    app.kubernetes.io/name: argocd-server

